-- Charge 3
CREATE VIEW
  VaptLibre AS
SELECT
  L.NO_IMMEUBLE,
  L.NO_LOGEMENT,
  L.LOYER
FROM
  LOGEMENTS L
  JOIN IMMEUBLES I ON L.NO_IMMEUBLE = I.NO_IMMEUBLE
WHERE
  L.NB_CHAMBRES = 3
  AND OCC_CODE = 'L'
  AND L.LOYER < 1750.00
  AND I.NB_LOGEMENTS >= 25;

-- Charge 4
CREATE VIEW
  Vreparation AS
SELECT DISTINCT
  L.NO_LOGEMENT,
  T.DESCRIPTION_METIER
FROM
  TAUX_METIERS T
  JOIN EMPLOYES EM ON T.CODE_METIER = EM.TAUX_CODE_METIER
  JOIN ENTRETIENS EN ON EM.EMP_NOM = EN.EMP_EMP_NOM
  JOIN LOGEMENTS L ON EN.LOG_NO_LOGEMENT = L.NO_LOGEMENT
  JOIN IMMEUBLES I ON L.NO_IMMEUBLE = I.NO_IMMEUBLE
WHERE
  L.FOYER = 'O'
  AND L.SALLE_A_DINER = 'N'
  AND I.VIL_NOM_VILLE IN ('Boucherville', 'St-Bruno')
  AND EN.ENT_DATE >= TO_DATE('2023-06-01', 'YYYY-MM-DD')
  AND EN.ENT_DATE <= TO_DATE('2023-06-25', 'YYYY-MM-DD');

-- Charge 5
CREATE VIEW
  VPetitApt AS
SELECT
  I.NO_IMMEUBLE,
  I.ADRESSE,
  I.NB_ETAGES,
  I.NB_LOGEMENTS,
  L.NB_CHAMBRES
FROM
  IMMEUBLES I
  JOIN LOGEMENTS L ON L.NO_IMMEUBLE = I.NO_IMMEUBLE
WHERE
  L.NB_CHAMBRES <= 2;

-- Charge 6
CREATE VIEW
  VConcierges AS
SELECT DISTINCT
  CON_NOM_CONCIERGE
FROM
  IMMEUBLES
  JOIN LOGEMENTS ON IMMEUBLES.NO_IMMEUBLE = LOGEMENTS.NO_IMMEUBLE
WHERE
  MEUBLE = 'S'
  AND OCC_CODE = 'C'
  AND VIL_NOM_VILLE = 'Longueuil'
ORDER BY
  CON_NOM_CONCIERGE DESC;

-- Charge 7
CREATE
OR REPLACE FUNCTION f_loyer (p_no_immeuble NUMBER) RETURN NUMBER IS v_revenu_total NUMBER := 0;

BEGIN
SELECT
  SUM(LOYER) INTO v_revenu_total
FROM
  LOGEMENTS
  JOIN LOCATAIRES ON LOGEMENTS.NO_IMMEUBLE = LOCATAIRES.LOG_NO_IMMEUBLE
WHERE
  NO_IMMEUBLE = p_no_immeuble
  AND TO_CHAR(DATE_ENTREE, 'MM') <= '06'
  AND TO_CHAR(DATE_FIN_BAIL, 'MM') >= 06
  AND TO_CHAR(DATE_ENTREE, 'YY') = '23'
  AND TO_CHAR(DATE_FIN_BAIL, 'YY') = '23';

RETURN v_revenu_total;

END;

/
CREATE OR REPLACE VIEW
  v_loyer AS
SELECT
  NO_IMMEUBLE,
  f_loyer (NO_IMMEUBLE) AS revenu_total
FROM
  IMMEUBLES;

-- Charge 8
CREATE
OR REPLACE PROCEDURE sp_archive (p_no_immeuble NUMBER) IS
BEGIN
INSERT INTO
  archives
SELECT
  i.NO_IMMEUBLE,
  i.ANNEE_EN_COURS,
  i.EVALUATION,
  ROUND(i.PRIX_ACHAT * v.TAUX_TAXES / 100, 2) AS TAXES,
  i.HYPOTHEQUE,
  i.CONCIERGERIE,
  i.ASSURANCE,
  i.ENTRETIEN,
  i.CUMUL_LOYER
FROM
  immeubles i
  JOIN villes v ON i.VIL_NOM_VILLE = v.NOM_VILLE
WHERE
  i.NO_IMMEUBLE = p_no_immeuble;

COMMIT;

END;

/
BEGIN sp_archive (1297);

END;

/
-- Charge 9
CREATE
OR REPLACE PROCEDURE sp_augmentation IS
BEGIN
UPDATE LOGEMENTS
SET
  LOYER = LOYER * 1.07
WHERE
  CHAUFFAGE = 'G';

END;

/ EXECUTE sp_augmentation;

-- Charge 10
DELETE FROM LOCATAIRES
WHERE
  DATE_FIN_BAIL < TO_DATE('2022-07-01', 'YYYY-MM-DD');